### ISSUE TITLE
BUG Using max_features as a list at forest level lacks support

### ISSUE THREAD

**Issue by PSSF23** [neurodata/treeple#188]
Code:

```python
FeatureImportanceForestClassifier(
    estimator=HonestForestClassifier(
        n_estimators=n_estimators,
        max_features=[0.3, 3],
        tree_estimator=MultiViewDecisionTreeClassifier(
            feature_set_ends=n_features_views,
            apply_max_features_per_feature_set=apply_max_features,
        ),
        random_state=seed,
        honest_fraction=honest_fraction,
        n_jobs=n_jobs,
    ),
    random_state=seed,
    test_size=test_size,
    sample_dataset_per_tree=sample_per_tree,
    stratify=stratify,
)
```

Error:

```python
Traceback (most recent call last):
 File "/Users/pssf23/GitHub/scikit-tree/build-install/usr/lib/python3.9/site-packages/sktree/tree/_honest_tree.py", line 577, in _fit
  self.estimator_._fit(
 File "/Users/pssf23/GitHub/scikit-tree/build-install/usr/lib/python3.9/site-packages/sktree/_lib/sklearn/tree/_classes.py", line 391, in _fit
  if self.max_features > 0.0:
TypeError: '>' not supported between instances of 'list' and 'float'
```

**Comment by adam2392** [comment]
This is unfortunately because HonestForest inherits from ForestClassifier and its error-checking code. There are a few solutions to this problem:

1. Overwrite the `_fit` function in HonestForestClassifier, so that way it does a more fancy `max_features` check as a function of the `tree_estimator` argument. I.e. it cannot be a list if not multiview
2. Document the usage properly in a short example and also the Notes section of the MultiViewDecisionTreeClassifier and HonestForestClassifier

**Comment by PSSF23** [comment]
seems fixed

**Comment by adam2392** [comment]
@PSSF23 how was it fixed?

**Comment by PSSF23** [comment]
@adam2392 I'm not sure. But the code works when I use Honest forest alone. Maybe FIFC is the buggy part?
