### ISSUE TITLE
Is sklearn2pmml supported by scikit-tree?

### ISSUE THREAD

**Issue by huangliqiao** [neurodata/treeple#255]
I tried to use sklearn2pmml to save the model trained by sktree.ensemble.ExtendedIsolationForest as pmml format, but it failed.

**versions:**
scikit-learn              1.4.0
scikit-tree               0.7.0
sklearn2pmml              0.105.2

**code:**
```python
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn.ensemble import IsolationForest
from sktree.ensemble import ExtendedIsolationForest

pipeline = PMMLPipeline([
 ("iforest", ExtendedIsolationForest(max_samples=128, random_state=0, n_jobs=-1, contamination=0.1))
])
 
# train
pipeline.fit(df_auto_train)
 
# import
sklearn2pmml(pipeline, "autotest_iforest.pmml")
```

**error:**
Standard output is empty
Standard error:
Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for sktree.tree._oblique_tree.ObliqueTree). This happens when an unsupported/unregistered class is being unpickled that requires construction arguments. Fix it by registering a custom IObjectConstructor for this class.
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
	at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:32)
	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:65)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:110)
	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:86)
	at com.sklearn2pmml.Main.run(Main.java:75)
	at com.sklearn2pmml.Main.main(Main.java:65)

**Comment by adam2392** [comment]
Hi @huangliqiao unsure! Never tried, and unfamiliar with sklearn2pmml. Are you able to provide some more information as to what is missing? 

Is it the pickling step, or something else?

**Comment by huangliqiao** [comment]
Hi Adam, thanks for replying. sktree works fine with pickle, but I need a model that can be loaded by Java. So I tried sklearn2pmml, and obviously it failed. Is there any workaround to save the scikit-tree model that can be used by Java?

**Comment by vruusmann** [comment]
Spotted this discussion, and it got me interested in exploring the concept of oblique trees.

Now, I've just released [SkLearn2PMML version 0.107.0](https://github.com/jpmml/sklearn2pmml/blob/master/NEWS.md#01070), which adds support for all Scikit-Tree's oblique decision tree estimator, and oblique decision tree ensemble estimator classes, including the `ExtendedIsolationForest` class.

Here's a demo:
``` python
from sklearn.datasets import load_iris
from sktree.ensemble import ExtendedIsolationForest

iris_X, iris_y = load_iris(return_X_y = True, as_frame = True)

eif = ExtendedIsolationForest(n_estimators = 13)
eif.fit(iris_X)

from sklearn2pmml import sklearn2pmml

sklearn2pmml(eif, "ExtendedIsolationForestIris.pmml")
```

So, I believe this issue can be closed as "fixed".

**Comment by adam2392** [comment]
@huangliqiao Let us know if the issue can be closed?

**Comment by adam2392** [comment]
Closing this issue as https://github.com/neurodata/scikit-tree/issues/263 was resolved. #262 is a separate topic, and can be discussed there.
